<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/koneksi.php';

// Script backup otomatis untuk cron job
// Jalankan setiap hari jam 2 pagi: 0 2 * * * /usr/bin/php /path/to/cron_backup.php

function backup_database(): string {
    global $koneksi;
    
    $nama_database = 'db-arfxtrade';
    $tanggal = date('Y-m-d_H-i-s');
    $nama_file = "backup_db_{$nama_database}_{$tanggal}.sql";
    $path_backup = __DIR__ . "/backup/{$nama_file}";
    
    // Buat direktori backup jika belum ada
    if (!is_dir(__DIR__ . '/backup')) {
        mkdir(__DIR__ . '/backup', 0755, true);
    }
    
    // Dapatkan daftar tabel
    $tables = [];
    $result = $koneksi->query("SHOW TABLES");
    while ($row = $result->fetch_array()) {
        $tables[] = $row[0];
    }
    
    $sql = "-- Backup Database: {$nama_database}\n";
    $sql .= "-- Tanggal: " . date('Y-m-d H:i:s') . "\n";
    $sql .= "-- Generated by ARFXTRADE Backup System\n\n";
    $sql .= "SET FOREIGN_KEY_CHECKS=0;\n\n";
    
    foreach ($tables as $table) {
        // Structure
        $sql .= "-- Struktur tabel `{$table}`\n";
        $sql .= "DROP TABLE IF EXISTS `{$table}`;\n";
        $result = $koneksi->query("SHOW CREATE TABLE `{$table}`");
        $row = $result->fetch_array();
        $sql .= $row[1] . ";\n\n";
        
        // Data
        $sql .= "-- Data tabel `{$table}`\n";
        $result = $koneksi->query("SELECT * FROM `{$table}`");
        if ($result->num_rows > 0) {
            $sql .= "INSERT INTO `{$table}` VALUES\n";
            $values = [];
            while ($row = $result->fetch_array()) {
                $row_values = array_map(function($value) use ($koneksi) {
                    return "'" . $koneksi->real_escape_string($value) . "'";
                }, $row);
                $values[] = "(" . implode(',', $row_values) . ")";
            }
            $sql .= implode(",\n", $values) . ";\n\n";
        }
    }
    
    $sql .= "SET FOREIGN_KEY_CHECKS=1;\n";
    
    // Simpan file
    file_put_contents($path_backup, $sql);
    
    // Hapus backup lama (lebih dari 30 hari)
    $files = glob(__DIR__ . "/backup/backup_db_*.sql");
    foreach ($files as $file) {
        if (filemtime($file) < time() - (30 * 24 * 60 * 60)) {
            unlink($file);
        }
    }
    
    return $nama_file;
}

// Jalankan backup
try {
    $nama_file = backup_database();
    echo "Backup berhasil: {$nama_file}\n";
    
    // Log ke file
    $log_file = __DIR__ . '/backup/backup.log';
    $log_message = date('Y-m-d H:i:s') . " - Backup berhasil: {$nama_file}\n";
    file_put_contents($log_file, $log_message, FILE_APPEND | LOCK_EX);
    
} catch (Exception $e) {
    echo "Error backup: " . $e->getMessage() . "\n";
    
    // Log error
    $log_file = __DIR__ . '/backup/backup.log';
    $log_message = date('Y-m-d H:i:s') . " - Error backup: " . $e->getMessage() . "\n";
    file_put_contents($log_file, $log_message, FILE_APPEND | LOCK_EX);
}
?>








